# Generated by Django 6.0.5 on 2026-05-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="tag",
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(to="firstApp.tag"),
        ),
    ]
