# Generated by Django 6.0.5 on 2026-05-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0003_projectlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("Graphics", "Graphics"),
                    ("Computations", "Computations"),
                    ("Software Development", "Software Development"),
                    ("Embeded System", "Embeded System"),
                ],
                default="Graphics",
                max_length=100,
            ),
        ),
    ]
