# Generated by Django 6.0.5 on 2026-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0004_project_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("Graphics", "Graphics"),
                    ("Computations", "Computations"),
                    ("Software Development", "Software Development"),
                    ("Embedded System", "Embedded System"),
                ],
                default="Graphics",
                max_length=100,
            ),
        ),
    ]
